### ISSUE TITLE
门窗状态和灯的状态一直不能配置正确

### ISSUE THREAD

**Issue by dx4wraith** [mirko3000/MMM-xiaomi#1]
把showWindow和showLights配置成文档中的值 都不能正常显示

**Comment by mirko3000** [comment]
English please :)

**Comment by dx4wraith** [comment]
Follow the configuration option，but showWindow and showLights can' display

**Comment by dx4wraith** [comment]
Follow the  Configuration options, but showWindow and showLights can't display

**Comment by mirko3000** [comment]
Can you post your configuration? What exactly is not displaying - the window and light status icon? Which devices do you have?
