### ISSUE TITLE
Xiaomi Aqara Window Door Sensor : not ok

### ISSUE THREAD

**Issue by smotx** [mirko3000/MMM-xiaomi#10]
Hi,

it seems that these window sensors are not compatible.

[Xiaomi Aqara Window Door Sensor](https://www.gearbest.com/access-control/pp_626703.html?lkid=10102456&vip=)

I added them to the config module and no return on MM.

When i launch

`miio discover`

it found

> Device ID: 158d0001ab1f9c
> Model info: lumi.magnet.aq2

but when i launch npm start, MMM-xiaomi say

`Found device with ID 158d0001ab1f9c of type generic`

and no

> Found device with ID 158d0001ab1f9c of type magnet

**Comment by mirko3000** [comment]
Yes the new aquara devices were not supported so far. I implemented a basic support with the latest version, please rerun "npm install" on your module folder. Let me know if it works.

**Comment by smotx** [comment]
ohhh, it's OK ! 

Beautiful 'star' when i open the door ! 

Thanks a lot
