### ISSUE TITLE
black screen on the mirror every time i install the module in config file

### ISSUE THREAD

**Issue by mattcasper** [mirko3000/MMM-xiaomi#11]
hello

i would really like to use this module but this far i've been unsuccessful, i copy the exact module from the README file, the mirror gives me a black screen every time and controls x doesn't work to close the mirror(i use pm2 to autostart it)
i tried multiple time, even on a new config file with no other module installed, it still doesn't work.

any help would be much appreciated
best regards

**Comment by mirko3000** [comment]
Hi, can you paste the configuration for the module here? Any output from the log or console?

**Comment by mattcasper** [comment]
i managed to make it work, unfortunately it doesn't seem to work with the aqara hub/app

**Comment by borland502** [comment]
Pity.  Yeah, I have an aqara hub as well.

**Comment by stankill** [comment]
i'm facing the same black screen issue.
Could you please tell us how you sort this out ?

**Comment by mirko3000** [comment]
Do you have the aqara hub or the Xiaomi hub?

**Comment by stankill** [comment]
I do have the xiaomi hub indeed.
Yet the sensors are not attached to it. Does it have an incidence ?

**Comment by mirko3000** [comment]
Not sure what is your exact issue. Did you install the sensors and they appear in the Mi Home app? Did you then follow the instructions here? Can you paste your config here?
