### ISSUE TITLE
Configuration options seems not to work

### ISSUE THREAD

**Issue by aurely89** [mirko3000/MMM-xiaomi#14]
Hi @mirko3000.
I've some problem with the options. Even if maxHumidity is set to 99 it still appears the refresh icon. Same for showWindow, when sensor is open it does not appear the star icon.

Devices have been recognized correctly and the token is also working since I can see temperature and humidity.

Configuration is the following: 

	},
		{
		module: "MMM-xiaomi",
		position: "top_left",
		header: "Temperatura / Umidità",
		config: {
			gatewayIP: "192.168.1.61",
			gatewayToken: "99d97673a38axxxxxxxxxxxxxxxx",
			showNotifications: true,
			showWindow: true,
			maxHumidity: "99",
			rooms: [
				{
					name: "Soggiorno",
					sortOrder: 10,
					devices: ["158d000201c07f", "158d0001f366cb"]
					},
				]
			}
		},

What could be wrong?

Thank you,
Flavio

**Comment by mirko3000** [comment]
Hi @aurely89,
The ventilation suggestion only works if you have an outdoor sensor configured (property outsideSensorId). If you do not have one, then the maxHumidity is probably ignored. I will check the code and probably do a small fix to get rid of the icon in this case.
Best regards,
Mirko

**Comment by aurely89** [comment]
Thank you @mirko3000 . I really appreciate your work.

Have a nice day,
Flavio
