### ISSUE TITLE
Possible to use this module with Conbee II ?

### ISSUE THREAD

**Issue by Masterg4941** [mirko3000/MMM-xiaomi#15]
Hello,

first off all thank you for this modul. It looks pretty nice and that´s why I really want to use it. 
My problem is that I don´t have a Xiaomi Gateway. I am working with Aqara/Xiaomi sensors which are connected to the Conbee II Gateway. Is it possible to integrate the Conbee Gateway as well?

Many thanks and greets

**Comment by mirko3000** [comment]
Hi there! That will most likely not work, this module is specifically for the Xiaomi gateway. You might adapt the Module if you can do a little programming, I do not know that gateway.
