### ISSUE TITLE
Possible to implement without Gateway

### ISSUE THREAD

**Issue by rubenix** [mirko3000/MMM-xiaomi#18]
Hello there,

I have no gateway, so Im looking for a way to show data from[ xiaomi hygrometer](https://www.aliexpress.com/item/4000713871310.html?spm=a2g0o.productlist.0.0.29e77ea4CINK7S&algo_pvid=6e371862-ca28-4f5b-8020-45a0484855c9&algo_expid=6e371862-ca28-4f5b-8020-45a0484855c9-0&btsid=0ab6fb8815872910320561196ec47f&ws_ab_test=searchweb0_0,searchweb201602_,searchweb201603_) to the Mirror.
So far i tested [this](https://github.com/JsBergbau/MiTemperature2) and can confirm its working with a pi3B via Bluetooth. Any way to implement this as a MM module? Thanks so much.

**Comment by rubinho101** [comment]
dito. I don't have a gateway either and want to integrate via BLE. Thanks in advance

**Comment by mirko3000** [comment]
Hi @rubenix, sure that would be possible. You would need to find a node module which wraps the python library to connect to the hygrometer via Bluetooth. But its a completely new module for MM, so nothing I can support from this module here.
