### ISSUE TITLE
how do i change the colour ?

### ISSUE THREAD

**Issue by gauka12345** [mirko3000/MMM-xiaomi#3]
hi one more question how do i change the colour of it all ? 
i would like to use fe0127 - white to make the temperature outstanding from all the modules 
i tried mod the css but it doesn't do anything , thanks for help 
Luk

**Comment by mirko3000** [comment]
Hi Luk, 

currently the temperature is styled with the default "dimmed" css class. You could override that in the MMM-xiaomi.css with this:
`.xm-xiaomi .dimmed {
  color: #FFFFFF;
}`

Best regards,
Mirko

**Comment by mirko3000** [comment]
Or any other css class within your project...

**Comment by gauka12345** [comment]
thank you that's worked perfectly ,  impressed with this module is amazing really good job !!
